package ru.surf.course.movierecommendations.tmdbTasks;

/**
 * Created by sergey on 14.12.16.
 */

public enum Tasks {
    SEARCH_BY_FILTER, SEARCH_BY_CUSTOM_FILTER, SEARCH_BY_NAME,
    SEARCH_BY_ID, SEARCH_BY_GENRE,
    SEARCH_SIMILAR, SEARCH_BY_KEYWORD,
    GET_MOVIE_CREDITS, GET_PERSON_BY_ID,
    GET_BACKDROPS, GET_POSTERS, GET_PROFILE_PICTURES,
    GET_MOVIE_GENRES, GET_TV_GENRES
}
